auth:
  permittedPaths:
    - "/test"
    - "/hello"
    - "/auth/login"
  idSecret: HDVP6MmawaeYtEan

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
postgres:
  datasource:
    password: postgres
    database: inventory_management
    username: postgres
    host: jdbc:postgresql://localhost:5432/short_projects
    className: org.postgresql.Driver
  connection-pool:
    maxSize: '9'
    connectionTimeOut: 250
    initialSize: '2'
    name: pg
    minIdle: 1
    maxLifeTime: 10
    validationQuery: SELECT 1

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

    web: TRACE
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 2880000

encoder:
  secret: M2zEsdugBL
  iteration: 33
  length: 256

